{block content}
<a href="{plink default}">&lt;&lt; home </a>
<div class="post">
    <h1>{$post['title']}</h1>
    <small>Přidáno {$post['date']|date}</small>
    <p>{$post['body']}</p>
</div>

<h3>Komentáře:</h3>
<div id="comments">
	{if count($comments)}
    <div id="comment-{$comment->id}" class="commment" n:foreach="$comments as $comment">
        <p>{$comment['body']}</p>
        <small>{$comment['author']}, {$comment['date']|date}</small>
        <hr>
    </div>
	{else}
	Ke článku zatím nebyly napsány žádné komentáře. Buďte první!
	{/if}
</div>

{control commentForm}