<?php

/**
 * Nette Framework - Profiler screen template.
 *
 * @copyright  Copyright (c) 2004, 2010 David Grudl
 * @license    http://nette.org/license  Nette license
 * @link       http://nette.org
 * @category   Nette
 * @package    Nette
 *
 * @param      array     $colophons
 * @return     void
 */

namespace Nette;

use Nette;

?>

<style type="text/css">#netteProfilerContainer{position:fixed;_position:absolute;right:5px;bottom:5px;z-index:23178}#netteProfiler{font:normal normal 11px/1.4 Consolas,Arial;position:relative;padding:3px;color:black;background:#EEE;border:1px dotted gray;cursor:move;opacity:.70;=filter:alpha(opacity=70)}#netteProfiler *{color:inherit;background:inherit;text-align:inherit}#netteProfilerIcon{position:absolute;right:0;top:0;line-height:1;padding:2px;color:black;text-decoration:none}#netteProfiler:hover{opacity:1;=filter:none}#netteProfiler ul{margin:0;padding:0;width:350px}#netteProfiler li{margin:0;padding:1px;text-align:left;list-style:none}#netteProfiler span[title]{border-bottom:1px dotted gray;cursor:help}#netteProfiler strong{color:red}</style>


<div id="netteProfilerContainer">
<div id="netteProfiler">
	<a id="netteProfilerIcon" href="#"><abbr>&#x25bc;</abbr></a
	><ul>
	<?php foreach ($colophons as $callback): ?>
	<?php foreach ((array) call_user_func($callback, 'profiler') as $line): ?><li><?php echo $line, "\n" ?></li><?php endforeach ?>
	<?php endforeach ?>
	</ul>
</div>
</div>


<script type="text/javascript">/*<![CDATA[*/document.getElementById("netteProfiler").onmousedown=function(c){c=c||event;this.posX=parseInt(this.style.left+"0");this.posY=parseInt(this.style.top+"0");this.mouseX=c.clientX;this.mouseY=c.clientY;var a=this;document.documentElement.onmousemove=function(b){b=b||event;a.style.left=b.clientX-a.mouseX+a.posX+"px";a.style.top=b.clientY-a.mouseY+a.posY+"px";return false};document.documentElement.onmouseup=function(){document.documentElement.onmousemove=null;document.documentElement.onmouseup=null;document.cookie=
"netteProfilerPosition="+a.style.left+":"+a.style.top+"; path=/";return false}};
document.getElementById("netteProfilerIcon").onclick=function(){var c=this.getElementsByTagName("abbr")[0],a=this.nextSibling,b=a.currentStyle?a.currentStyle.display=="none":getComputedStyle(a,null).display=="none";c.innerHTML=b?String.fromCharCode(9660):"Profiler "+String.fromCharCode(9658);a.style.display=b?"block":"none";c.parentNode.style.position=b?"absolute":"static";document.cookie="netteProfilerVisible="+b*1+"; path=/";return false};document.body.appendChild(document.getElementById("netteProfilerContainer"));
document.cookie.indexOf("netteProfilerVisible=0")>-1&&document.getElementById("netteProfilerIcon").onclick();var _nettePos=document.cookie.match(/netteProfilerPosition=([0-9-]+px):([0-9-]+px)/);if(_nettePos){document.getElementById("netteProfiler").style.left=_nettePos[1];document.getElementById("netteProfiler").style.top=_nettePos[2]};/*]]>*/</script>
